### ISSUE TITLE
chart data

### ISSUE THREAD

**Issue by zefanja** [cdscacth/AQI#4]
It looks like that the chart just loads fine every time. Can't we use that data for AQI calculations and just update the AQI if we get the other - more up to date - data?

**Comment by aPinat** [comment]
Well... The chart isn't being on the kiosk page; and actually the php script behind the chart data requests the data in the exact same way... Sometimes turning off the chart helps loading the CDSC data on the main page, but very inconsistently, and somehow it doesn't seam to make a big difference...
But I think we could go for #3, because the kiosk-page often enough returns CDSC data.

Plus, right now, they're actually two separated functions (which would be changeable though).

**Comment by zefanja** [comment]
Ok, than focus on #3
